// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Clients
{
    public int Id { get; set; }

    public bool IsMember { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public DateTime? Birthdate { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public int? IdGenderDenomination { get; set; }

    public string Address { get; set; }

    public string ZipCode { get; set; }

    public int? IdMaritalStatus { get; set; }

    public int? IdFamilySituation { get; set; }

    public int? AdultsAtHome { get; set; }

    public int? ChildsAtHome { get; set; }

    public int? IdHabitationType { get; set; }

    public int? IdBank { get; set; }

    public int? IdEmploymentSituation { get; set; }

    public int? IdScholarshipType { get; set; }

    public byte[] Income { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public virtual ICollection<ClientsAttachments> ClientsAttachments { get; set; } = new List<ClientsAttachments>();

    public virtual ICollection<ClientsIncomeTypes> ClientsIncomeTypes { get; set; } = new List<ClientsIncomeTypes>();

    public virtual ICollection<ClientsNotes> ClientsNotes { get; set; } = new List<ClientsNotes>();

    public virtual MdBank IdBankNavigation { get; set; }

    public virtual MdEmploymentSituation IdEmploymentSituationNavigation { get; set; }

    public virtual MdFamilySituation IdFamilySituationNavigation { get; set; }

    public virtual MdGenderDenomination IdGenderDenominationNavigation { get; set; }

    public virtual MdHabitationType IdHabitationTypeNavigation { get; set; }

    public virtual MdMaritalStatus IdMaritalStatusNavigation { get; set; }

    public virtual MdScholarshipType IdScholarshipTypeNavigation { get; set; }

    public virtual ICollection<Interventions> Interventions { get; set; } = new List<Interventions>();

    public virtual ICollection<SeminarsParticipants> SeminarsParticipants { get; set; } = new List<SeminarsParticipants>();
}