// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class ClientsAttachments
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    public int? IdEmployee { get; set; }

    public string FileName { get; set; }

    public byte[] FileContent { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual Employees IdEmployeeNavigation { get; set; }
}