// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class CowMilkProductionTypes
{
    public int Id { get; set; }

    public int IdCowMilkIngredientPriceList { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public virtual ICollection<CowMilkSalesGeneralInfoProductions> CowMilkSalesGeneralInfoProductions { get; set; } = new List<CowMilkSalesGeneralInfoProductions>();

    public virtual CowMilkIngredientPriceLists IdCowMilkIngredientPriceListNavigation { get; set; }
}