// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class CowMilkIngredientPriceListMonths
{
    public int Id { get; set; }

    public int IdCowMilkIngredientPriceList { get; set; }

    public int IdCowMilkIngredient { get; set; }

    public DateTime EffectiveMonthDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public decimal Dcpercentage { get; set; }

    public byte[] Amount { get; set; }

    public virtual CowMilkIngredients IdCowMilkIngredientNavigation { get; set; }

    public virtual CowMilkIngredientPriceLists IdCowMilkIngredientPriceListNavigation { get; set; }
}