// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class CowMilkIngredientPriceLists
{
    public int Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string Name { get; set; }

    public virtual ICollection<CowMilkIngredientPriceListMonths> CowMilkIngredientPriceListMonths { get; set; } = new List<CowMilkIngredientPriceListMonths>();

    public virtual ICollection<CowMilkProductionTypes> CowMilkProductionTypes { get; set; } = new List<CowMilkProductionTypes>();
}