// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class CowMilkSalesGeneralInfoProductions
{
    public int Id { get; set; }

    public int IdCowMilkSalesGeneralInfo { get; set; }

    public int IdCowMilkProductionType { get; set; }

    public int DaysOverQuota { get; set; }

    public decimal ProductionBonus { get; set; }

    public virtual CowMilkProductionTypes IdCowMilkProductionTypeNavigation { get; set; }

    public virtual CowMilkSalesGeneralInfos IdCowMilkSalesGeneralInfoNavigation { get; set; }
}