// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class CowMilkIngredients
{
    public int Id { get; set; }

    public int IdProductionTypeDeparment { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string UnitDisplayName { get; set; }

    public decimal DefaultDcperTon { get; set; }

    public virtual ICollection<CowMilkIngredientPriceListMonths> CowMilkIngredientPriceListMonths { get; set; } = new List<CowMilkIngredientPriceListMonths>();

    public virtual ProductionTypeDepartments IdProductionTypeDeparmentNavigation { get; set; }
}