// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class EmployeePermissions
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public bool? AllowInterventions { get; set; }

    public bool? AllowReports { get; set; }

    public bool? AllowSu { get; set; }

    public virtual Employees Employee { get; set; }
}