// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Employees
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<ClientsAttachments> ClientsAttachments { get; set; } = new List<ClientsAttachments>();

    public virtual ICollection<ClientsNotes> ClientsNotes { get; set; } = new List<ClientsNotes>();

    public virtual ICollection<EmployeePermissions> EmployeePermissions { get; set; } = new List<EmployeePermissions>();

    public virtual ICollection<Interventions> Interventions { get; set; } = new List<Interventions>();

    public virtual ICollection<InterventionsAttachments> InterventionsAttachments { get; set; } = new List<InterventionsAttachments>();

    public virtual ICollection<InterventionsNotes> InterventionsNotes { get; set; } = new List<InterventionsNotes>();

    public virtual ICollection<SeminarsEmployees> SeminarsEmployees { get; set; } = new List<SeminarsEmployees>();
}