// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Interventions
{
    public int Id { get; set; }

    public bool? IsVirtual { get; set; }

    public DateTime? DateIntervention { get; set; }

    public int? IdEmployee { get; set; }

    public int? IdClient { get; set; }

    public int? IdReferenceType { get; set; }

    public int? IdStatusType { get; set; }

    public int? IdInterventionType { get; set; }

    public byte[] DebtAmount { get; set; }

    public int? IdLoanReason { get; set; }

    public bool? IsLoanPaid { get; set; }

    public byte[] LoanAmount { get; set; }

    public byte[] LoanAmountBalance { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual Employees IdEmployeeNavigation { get; set; }

    public virtual MdInterventionType IdInterventionTypeNavigation { get; set; }

    public virtual MdLoanReason IdLoanReasonNavigation { get; set; }

    public virtual MdReferenceSource IdReferenceTypeNavigation { get; set; }

    public virtual MdInterventionStatusTypes IdStatusTypeNavigation { get; set; }

    public virtual ICollection<InterventionsAttachments> InterventionsAttachments { get; set; } = new List<InterventionsAttachments>();

    public virtual ICollection<InterventionsInterventionSolutions> InterventionsInterventionSolutions { get; set; } = new List<InterventionsInterventionSolutions>();

    public virtual ICollection<InterventionsNotes> InterventionsNotes { get; set; } = new List<InterventionsNotes>();
}