// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccess.Models
{
    public partial interface IProjet_CLContextProcedures
    {
        List<DecryptDataResult> DecryptData(byte[] Data, string Key, OutputParameter<string> ReturnValue, OutputParameter<int> returnValue = null);
        List<EncryptDataResult> EncryptData(string Data, string Key, OutputParameter<byte[]> ReturnValue, OutputParameter<int> returnValue = null);
        List<GenerateNewIDResult> GenerateNewID(string sequenceName, OutputParameter<int> returnValue = null);
    }
}
