// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class MdInterventionSolution
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<InterventionsInterventionSolutions> InterventionsInterventionSolutions { get; set; } = new List<InterventionsInterventionSolutions>();
}