// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class MdInterventionStatusTypes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<Interventions> Interventions { get; set; } = new List<Interventions>();
}