// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class ProductionTypeDepartments
{
    public int Id { get; set; }

    public int IdProductionType { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public int PurchaseVisualOrder { get; set; }

    public bool HasRecipeDetailedDescrption { get; set; }

    public string AmoutUnitDisplayName { get; set; }

    public string ShortDisplayName { get; set; }

    public virtual ICollection<CowMilkIngredients> CowMilkIngredients { get; set; } = new List<CowMilkIngredients>();

    public virtual ProductionTypes IdProductionTypeNavigation { get; set; }
}