// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class SeminarsParticipants
{
    public int Id { get; set; }

    public int? IdSeminar { get; set; }

    public int? IdClient { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual Seminars IdSeminarNavigation { get; set; }
}