// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Seminars
{
    public int Id { get; set; }

    public DateTime? DateSeminar { get; set; }

    public int? IdSeminarTheme { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual MdSeminarThemes IdSeminarThemeNavigation { get; set; }

    public virtual ICollection<SeminarsEmployees> SeminarsEmployees { get; set; } = new List<SeminarsEmployees>();

    public virtual ICollection<SeminarsParticipants> SeminarsParticipants { get; set; } = new List<SeminarsParticipants>();
}