// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class SeminarsEmployees
{
    public int Id { get; set; }

    public int? IdSeminar { get; set; }

    public int? IdEmployee { get; set; }

    public virtual Employees IdEmployeeNavigation { get; set; }

    public virtual Seminars IdSeminarNavigation { get; set; }
}