name: .NET Core Deploy to IIS

on: 
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
  

    # Installe le SDK .NET Core 6.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Build le projet depuis le chemin réseau distant
    - name: Build with dotnet
      run: dotnet build --configuration Release "\\tsclient\F\EcoleTemporaire\AcefFinal\ACEF\WebApp\WebApp.csproj"

    # Publie le projet dans un dossier de publication
    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o dotnetcorewebapp "\\tsclient\F\EcoleTemporaire\AcefFinal\ACEF\WebApp\WebApp.csproj"

    # Redémarre IIS pour s'assurer que les nouveaux fichiers sont pris en compte
    - name: Restart IIS
      run: |
        iisreset /stop
        iisreset /start

    # Teste si le site est bien en ligne
    - name: Curl the website as a smoke test
      run: curl http://localhost/PublishAcef
