name: .NET Core Deploy to IIS

on: 
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
  

    # Installe le SDK .NET Core 6.0 (si nécessaire pour d'autres étapes futures)
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Si les fichiers sont déjà publiés manuellement, on saute la publication
    # Redémarre IIS pour appliquer les modifications
    - name: Restart IIS
      run: |
        iisreset /stop
        iisreset /start

    # Teste si le site est bien en ligne
    - name: Curl the website as a smoke test
      run: curl http://localhost/PublishAcef
